[package]
name = "frede/resource-gathering-simulator"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.4.7"
Cmdr = "evaera/cmdr@1.9.0"
Janitor = "howmanysmall/janitor@1.14.1"
Signal = "sleitnick/signal@1.2.1"
Roact = "roblox/roact@1.4.4"
Roact-Rodux = "roblox/roact-rodux@0.3.0"
Rodux = "roblox/rodux@3.0.0"
ProfileService = "surnautica/profileservice@1.0.0"
Promise = "evaera/promise@4.0.0"