[package]
name = "frede/resource-gathering-simulator"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.4.7"
Cmdr = "evaera/cmdr@1.9.0"
Janitor = "howmanysmall/janitor@1.14.1"
Signal = "sleitnick/signal@1.2.1"
ProfileService = "surnautica/profileservice@1.0.0"
Promise = "evaera/promise@4.0.0"
CameraShaker = "brittonfischer/camerashaker@0.1.0"
Roact = "roblox/roact@1.4.4"
RoactHooks = "kampfkarren/roact-hooks@0.5.0"
RoactSpring = "chriscerie/roact-spring@1.0.1"